application: time-vault
version: 1
runtime: go
api_version: go1

handlers:
- url: /_ah/queue/go/.*
  script: _go_app
  login: admin
  secure: always

- url: /api/.*
  script: _go_app
  secure: always

- url: /views
  static_dir: angular/dist/views
  secure: always

- url: /scripts
  static_dir: angular/dist/scripts
  secure: always

- url: /styles
  static_dir: angular/dist/styles
  secure: always

- url: /images
  static_dir: angular/dist/images
  secure: always

- url: /bower_components
  static_dir: angular/dist/bower_components
  secure: always

- url: /
  static_files: angular/dist/index.html
  upload: angular/dist/index.html
  secure: always
