application: time-vault
version: 1
runtime: go
api_version: go1

handlers:
- url: /_ah/queue/go/.*
  script: _go_app
  login: admin
  secure: always

- url: /api/.*
  script: _go_app
  secure: always

- url: /assets
  static_dir: assets
  secure: always

- url: /.*
  static_files: static/index.html
  upload: static/index.html
  secure: always
