application: time-vault
version: 1
runtime: go
api_version: go1

handlers:
- url: /_ah/queue/go/.*
  script: _go_app
  login: admin
  secure: always

- url: /api/.*
  script: _go_app
  secure: always

- url: /views
  static_dir: angular/app/views
  secure: always

- url: /scripts
  static_dir: angular/.tmp/scripts
  secure: always

- url: /styles
  static_dir: angular/.tmp/styles
  secure: always

- url: /images
  static_dir: angular/app/images
  secure: always

- url: /bower_components
  static_dir: angular/bower_components
  secure: always

- url: /.*
  static_files: angular/app/index.html
  upload: angular/app/index.html
  secure: always
