application: time-vault
module: default
version: 1
runtime: go
api_version: go1
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^.sass-cache\/.*
- ^.tmp\/.*
- ^.app\/.*
- ^.bower_components\/.*
- ^node_modules\/.*
- ^test\/.*

handlers:
- url: /views
  static_dir: dist/views
  secure: always

- url: /scripts
  static_dir: dist/scripts
  secure: always

- url: /styles
  static_dir: dist/styles
  secure: always

- url: /images
  static_dir: dist/images
  secure: always

- url: /bower_components
  static_dir: dist/bower_components
  secure: always

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
