application: time-vault
module: default
version: 1
runtime: go
api_version: go1

handlers:
- url: /views
  static_dir: app/views
  secure: always

- url: /scripts
  static_dir: .tmp/scripts
  secure: always

- url: /styles
  static_dir: .tmp/styles
  secure: always

- url: /images
  static_dir: app/images
  secure: always

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /.*
  static_files: app/index.html
  upload: app/index.html
  secure: always
